/**
 * TypeScript type declarations for parsers generated by PEG.js.
 */

declare module parser {
    /**
     * Run the parser.
     */
    function parse(input: string, options?: Object): any;

    class SyntaxError {
        public name: string;
        public message: string;
        public expected: string;
        public found: string;
        public location: {
          start: { offset: number, line: number, column: number };
          end: { offset: number, line: number, column: number };
        };
    }
}

export = parser;
